name: Pipe

on:
  push:
      branches:
        - main

jobs:
  lint:
    runs-on: 'ubuntu-latest'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: install flake
        run: |
          python -m pip install --upgrade pip
          pip install flake8
      - name: run flake
        run: flake8 .


